#Babe AI Course Project
# - Herlina Prastiwi-

In [1]:
#first we install pandas 
!pip install pandas

# Data Loading

In [2]:
# we connect google colab to our drive

from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [3]:
#connect to directory where we store the data

import os
os.listdir(os.path.join('gdrive', 'My Drive', 'pelatihanAI', 'course2'))

['test.json', 'train.json', 'test_result.json']

In [0]:
#in this case, we need to load train.json as data training and test_result.json as data testing


data_dir = os.path.join('gdrive', 'My Drive', 'pelatihanAI', 'course2')

# Reading training & testing data
train_file = os.path.join(data_dir, 'train.json')
test_file = os.path.join(data_dir, 'test_result.json')


# Data Reading

In [0]:
def read_lines(filepath):
    with open(filepath) as fp:
        content = fp.readlines()
    return content

In [12]:
#Reading the files

train_file = read_lines(train_file)
test_file = read_lines(test_file)
print(len(train_file))
print(len(test_file))

250162
62543


In [13]:
for i in range(10):
  print(train_file[i])

{"category": "other", "text": "MANTAP.. Resep Sayur Asem Non MSG", "id": "6449487861220639243"}

{"category": "other", "text": "Rontgen : Foto Polos Abdomen", "id": "6460539363649389068"}

{"category": "entertainment", "text": "Artis dan Ratusan Warga Antar Jupe ke Peristirahatan Terakhir", "id": "6429995244539871755"}

{"category": "other", "text": "15 September 2017 (Sai Bumi): Pokbal dan Gojek Diminta Bersatu", "id": "6465950412347277580"}

{"category": "other", "text": "Keren Banget! Cara Pasang Keramik di Lantai dan di Tembok Bisa Licin dan Rapih Kaya Kaca", "id": "6471148464041361675"}

{"category": "other", "text": "Video Lucu Banget Bikin Ngakak Very Funny Cats 25", "id": "6458335623458587147"}

{"category": "other", "text": "Terbaru:Penjelasan Cesar dan Mas Eko", "id": "6458785036953977355"}

{"category": "other", "text": "Terungkap! Ada Seorang Bocah \u2018Berwajah Nenek nenek\u2019", "id": "6441497481564914188"}

{"category": "other", "text": "Tak Nyaman dan Merdeka di Indon

In [0]:
import pandas as pd

In [15]:
import ast
train_file_list_dict = []
for item in train_file:
  data = ast.literal_eval(item)
  train_file_list_dict.append(data)
  
test_file_list_dict = []
for item in test_file:
  data = ast.literal_eval(item)
  test_file_list_dict.append(data)
  
  
print(len(train_file_list_dict))
print(len(test_file_list_dict))
print(type(train_file_list_dict))
print(type(test_file_list_dict))

250162
62543
<class 'list'>
<class 'list'>


In [16]:
print(type(train_file_list_dict[0]))

<class 'dict'>


In [0]:
# Make DataFrame to each file (train & test)

train = pd.DataFrame.from_records(train_file_list_dict)
test = pd.DataFrame.from_records(test_file_list_dict)

In [19]:
train.head(10)

category                   id  \
0          other  6449487861220639243   
1          other  6460539363649389068   
2  entertainment  6429995244539871755   
3          other  6465950412347277580   
4          other  6471148464041361675   
5          other  6458335623458587147   
6          other  6458785036953977355   
7          other  6441497481564914188   
8          other  6454574697462891020   
9          other  6466025808237429003   

                                                text  
0                  MANTAP.. Resep Sayur Asem Non MSG  
1                       Rontgen : Foto Polos Abdomen  
2  Artis dan Ratusan Warga Antar Jupe ke Peristir...  
3  15 September 2017 (Sai Bumi): Pokbal dan Gojek...  
4  Keren Banget! Cara Pasang Keramik di Lantai da...  
5  Video Lucu Banget Bikin Ngakak Very Funny Cats 25  
6               Terbaru:Penjelasan Cesar dan Mas Eko  
7  Terungkap! Ada Seorang Bocah ‘Berwajah Nenek n...  
8  Tak Nyaman dan Merdeka di Indonesia, Tokoh FPI...  
9              Zidane Sampaikan Pujian untuk Ronaldo

In [20]:
test.head(10)

category                   id  \
0          other  6473785241143083275   
1          other  6461917851224637963   
2          other  6496294613593096459   
3          other  6497968982073540876   
4  entertainment  6434784167824720396   
5          other  6496264790460072204   
6          other  6482592695389782283   
7          other  6458056059859763724   
8  entertainment  6432623656135819788   
9          other  6450744042866082316   

                                                text  
0                            Nggak Cuma Surga Wisata  
1                            Chicken in Hoisin Sauce  
2  Karena Tidak Pasang Bok Vilter Udara Yamaha Mi...  
3  2018 new Ducati Multistrada 1260S Gran Canaria...  
4  Taecyeon 2PM Kejutkan Penggemar dengan Penampi...  
5             Mkgr Gelar Diklat Perempuan dan Pemilu  
6  Sang Mesin Gol Bali United Comvalius Satu Gol ...  
7  Pidato Sukarno - Pesan Kemerdekaan Untuk Indon...  
8  Konyol! Ini 9 Potret Kesalahan Saat Pernikahan...  
9  Dilarikan ke Ruang Tindakan, Jupe Tak Sadarkan...

In [21]:
print(type(train))

<class 'pandas.core.frame.DataFrame'>


In [22]:
#we look how many categories that the training data have, these are 4 categories.

train.category.unique()

array(['other', 'entertainment', 'funny', 'sport'], dtype=object)

In [24]:
print(train.sample(20))

             category                   id  \
129144          other  6459374811461190155   
23010           other  6458053241753043467   
126463          other  6450793048195465739   
108025          other  6467632979685409035   
23475   entertainment  6427634692006085132   
48298           other  6499259499755340044   
86121           other  6450754846696931851   
94061           other  6458378156167397899   
33422           other  6454804550485295627   
180865          other  6499092133012570379   
229366          other  6476284315159232779   
210899          other  6476417195730534667   
141370          other  6455090321486250508   
237946          other  6460472974116913676   
17954           other  6489814964281278732   
141658          other  6459519711666242060   
143676          other  6441484463883944459   
4092            other  6463487908685807883   
23737           other  6485967736395530507   
131109          other  6468575828048347403   

                                 

# Stop Words Loading

In [0]:
def load_stop_words():
  # Get the set of stopwords
  stop_words_f = os.path.join('gdrive', 'My Drive', 'LogisticRegression', 'data', 'dicts', 'stop_words.txt')

  flines = read_lines(stop_words_f)
  return set([x.strip() for x in flines])

In [26]:
stop_words = load_stop_words()
print(len(stop_words))

7193


# Data Cleansing

In [0]:
# For data cleansing

from bs4 import BeautifulSoup
import re

# text cleansing function
def raw_to_words(raw_text, stop_words=None):
    # 1. Remove HTML
    text_1 = BeautifulSoup(raw_text).get_text()
    
    # 2. Remove non-letters with regex
    letters_only = re.sub("[^a-zA-Z]", " ", text_1)
    
    # 3. Convert to lower case, split into individual words
    words = letters_only.lower().split()
    
    # 4. Remove stop words
    if stop_words:
        meaningful_words = [w for w in words if not w in stop_words]   
    else:
        meaningful_words = words
    
    # 5. Join the words back into one string separated by space & return
    return(" ".join(meaningful_words))

In [31]:
# we train the the data to remove the stop words

train_data_stop_words = ast.literal_eval(train_file[100])
print(train_data_stop_words["text"])
print(raw_to_words(train_data_stop_words["text"], stop_words=stop_words))

Nastusha Bisa Naik Tangga Pinter Yaa
nastusha naik tangga pinter


In [32]:
# clean the data from the stop words

clean_data_train = train
clean_data_train['text'] = clean_data_train['text'].apply(raw_to_words, stop_words=stop_words)
clean_data_train = clean_data_train.loc[clean_data_train['text']!='']
print(clean_data_train.head())

        category                   id  \
0          other  6449487861220639243   
1          other  6460539363649389068   
2  entertainment  6429995244539871755   
3          other  6465950412347277580   
4          other  6471148464041361675   

                                                text  
0                    mantap resep sayur asem non msg  
1                         rontgen foto polos abdomen  
2   artis ratusan warga jupe peristirahatan terakhir  
3    september sai bumi pokbal gojek diminta bersatu  
4  keren banget cara pasang keramik lantai tembok...  


In [33]:
clean_data_test = test
clean_data_test['text'] = clean_data_test['text'].apply(raw_to_words, stop_words=stop_words)
clean_data_test = clean_data_test.loc[clean_data_test['text']!='']
print(clean_data_test.head())

        category                   id  \
0          other  6473785241143083275   
1          other  6461917851224637963   
2          other  6496294613593096459   
3          other  6497968982073540876   
4  entertainment  6434784167824720396   

                                                text  
0                                 nggak surga wisata  
1                               chicken hoisin sauce  
2  pasang vilter udara yamaha mio akibatnya ganti...  
3  new ducati multistrada s gran canaria test photos  
4  taecyeon pm kejutkan penggemar penampilannya f...  


In [34]:
clean_data_train.shape

(250116, 3)

In [35]:
clean_data_test.shape

(62534, 3)

In [36]:
from sklearn import model_selection, preprocessing, linear_model, naive_bayes, metrics, svm
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn import decomposition, ensemble

import pandas, xgboost, numpy, textblob, string
from keras.preprocessing import text, sequence
from keras import layers, models, optimizers

Using TensorFlow backend.


# Object Vectorized

In [37]:
# making the label
cat_encoder = preprocessing.LabelEncoder()
cat_encoder.fit(train.category.unique())

LabelEncoder()

In [0]:
train_x, valid_x, train_y, valid_y = model_selection.train_test_split(clean_data_train['text'], cat_encoder.transform(clean_data_train['category']))

In [0]:
# create a count vectorizer object 
count_vect = CountVectorizer(analyzer='word', token_pattern=r'\w{1,}')

In [40]:
print(type(count_vect))

<class 'sklearn.feature_extraction.text.CountVectorizer'>


In [41]:
count_vect.fit(clean_data_train['text'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='\\w{1,}', tokenizer=None,
        vocabulary=None)

In [42]:
count_vect.fit(clean_data_test['text'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='\\w{1,}', tokenizer=None,
        vocabulary=None)

In [0]:
# implementing vetorized object to data training & testing

xtrain_count =  count_vect.transform(train_x)
xvalid_count =  count_vect.transform(valid_x)

In [44]:
import numpy as np

# catatan ::

print(train_x.shape)

print(len(count_vect.vocabulary_))
print(count_vect.get_feature_names())

print(xtrain_count.shape)

(187587,)
46186
['a', 'aaaaaaakkkkkkkkkkkk', 'aabatam', 'aabs', 'aacara', 'aadc', 'aadeci', 'aadesh', 'aadk', 'aal', 'aaliyah', 'aamiin', 'aamir', 'aampe', 'aang', 'aap', 'aaron', 'aasam', 'aau', 'abad', 'abadhan', 'abadi', 'abadikan', 'abadisejatindo', 'abaikan', 'abakura', 'abal', 'abandoned', 'abang', 'abangnya', 'abar', 'abarth', 'abas', 'abaya', 'abbas', 'abbasi', 'abboud', 'abc', 'abcd', 'abcselfiecompetition', 'abd', 'abdee', 'abdel', 'abdi', 'abdoel', 'abduh', 'abdul', 'abdulaziz', 'abdulgani', 'abdulrachman', 'abdur', 'abdurrahman', 'abdya', 'abe', 'abean', 'abed', 'abel', 'abenetwork', 'abenk', 'abenteuer', 'abepura', 'abg', 'abhishek', 'abi', 'abid', 'abidin', 'abies', 'abiezz', 'abigail', 'abih', 'abiiiiis', 'abiiiis', 'abiiiss', 'abiiisss', 'abiisss', 'abiiz', 'ability', 'abimana', 'abio', 'abirama', 'abis', 'abisan', 'abisnya', 'abiss', 'abisss', 'abissss', 'abiyu', 'abiz', 'abizz', 'abizzz', 'abizzzz', 'abjad', 'abk', 'abls', 'abm', 'abnonku', 'abnormal', 'aboge', 'aboli

In [45]:
print(xtrain_count.__dir__)
print(xtrain_count.__dict__)

<built-in method __dir__ of csr_matrix object at 0x7fcd7f013198>
{'_shape': (187587, 46186), 'maxprint': 50, 'indices': array([ 1924, 10429, 16350, ...,  2918, 35194, 42073], dtype=int32), 'indptr': array([      0,      10,      18, ..., 1141081, 1141090, 1141093],
      dtype=int32), 'data': array([1, 1, 1, ..., 1, 1, 1]), '_has_sorted_indices': True}


In [0]:
%matplotlib inline 
# import Modules that we will use to make Data Modeling
import matplotlib.pyplot as plt, re
import warnings; warnings.simplefilter('ignore')
import numpy as np, pandas as pd, seaborn as sns; sns.set()
from tqdm import tqdm
from tensorflow.python.client import device_lib
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers.embeddings import Embedding
from keras import layers
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout, Activation, Flatten, Conv1D, MaxPooling1D
from sklearn.datasets import fetch_20newsgroups
from nltk import sent_tokenize
from textblob import TextBlob

# Data Modelling

In [69]:

# Creating the Model
# in this case, we use Neuron Network to solve this problem

units=128
learning_rate=1e-3


model = keras.Sequential([
    #Input + 1st Hidden Layer
    keras.layers.Dense(64, activation=tf.nn.relu, input_shape=[len(count_vect.vocabulary_)]),
    #Hidden layer again
    keras.layers.Dense(units, activation=tf.nn.relu),
    #Output
    keras.layers.Dense(len(train.category.unique()), activation=tf.nn.softmax)
])

model.compile(optimizer=tf.keras.optimizers.Adam(lr=learning_rate), 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.summary()




_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_18 (Dense)             (None, 64)                2955968   
_________________________________________________________________
dense_19 (Dense)             (None, 128)               8320      
_________________________________________________________________
dense_20 (Dense)             (None, 4)                 516       
Total params: 2,964,804
Trainable params: 2,964,804
Non-trainable params: 0
_________________________________________________________________


In [70]:
callbacks = [keras.callbacks.EarlyStopping(monitor='val_acc', patience=2)]

# Proses
model.fit(xtrain_count, train_y, batch_size=32, epochs=40,
         validation_data=(xvalid_count, valid_y), callbacks=callbacks)

Train on 187587 samples, validate on 62529 samples
Epoch 1/40
187587/187587 [==============================] - 63s 338us/sample - loss: 0.2090 - acc: 0.9261 - val_loss: 0.1784 - val_acc: 0.9303
Epoch 2/40
187587/187587 [==============================] - 66s 353us/sample - loss: 0.1345 - acc: 0.9442 - val_loss: 0.1972 - val_acc: 0.9299
Epoch 3/40
187587/187587 [==============================] - 66s 353us/sample - loss: 0.0977 - acc: 0.9595 - val_loss: 0.2150 - val_acc: 0.9256


In [0]:
# implementing countvectrizer
import numpy as np

x_test = count_vect.transform(clean_data_test['text'])
y_test = cat_encoder.transform(clean_data_test['category'])

y_test_prob = model.predict(x_test)
y_test_pred = np.argmax(y_test_prob, axis=1)

# Summary

In [51]:
true_match = np.sum(y_test == y_test_pred)

#print the accuration
accuration = true_match/len(y_test)
print(accuration)


#print metrics of our built model
print("Validation set")

print('Confusion Matrix : \n' + str(metrics.confusion_matrix(y_test, y_test_pred)))
print("Report:\n", metrics.classification_report(y_test, y_test_pred, target_names=cat_encoder.classes_))


0.924457095340135
Validation set
Confusion Matrix : 
[[ 2530    15   750     6]
 [   10  1675   604     1]
 [  806   626 53367   548]
 [    7     6  1345   238]]
Report:
                precision    recall  f1-score   support

entertainment       0.75      0.77      0.76      3301
        funny       0.72      0.73      0.73      2290
        other       0.95      0.96      0.96     55347
        sport       0.30      0.15      0.20      1596

    micro avg       0.92      0.92      0.92     62534
    macro avg       0.68      0.65      0.66     62534
 weighted avg       0.92      0.92      0.92     62534



after these steps we see the final result, 
the "other" category has the highest accuration among 3 other categories and it's followed by "entertainment" and also "funny" category.
The "sport" category has the lowest accuration among 3 other categories.


##What makes those categories have different accuration level ?

Now, let we check how many data that each category has!

In [52]:
np.sum(clean_data_train['category'] == 'entertainment')

13203

In [53]:
np.sum(clean_data_train['category'] == 'other')

221377

In [54]:
np.sum(clean_data_train['category'] == 'sport')

6382

In [55]:
np.sum(clean_data_train['category'] == 'funny')

9154

##After checking the amount of data that each category has, we can conclude that imbalance of data makes various accuration.

##The "other" category has the highest amount of data which it also has the highest accuration.
and...
##The "sport" category has the lowest amount of data which it also has the lowest accuration.

#from this case, we learn that the imbalance of data is also affected the data accuration.

